/*
 Navicat Premium Data Transfer

 Source Server         : 182-pg
 Source Server Type    : PostgreSQL
 Source Server Version : 100003
 Source Host           : 172.16.98.182:5432
 Source Catalog        : ding-robot
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100003
 File Encoding         : 65001

 Date: 05/01/2021 16:56:53
*/


-- ----------------------------
-- Table structure for support
-- ----------------------------
DROP TABLE IF EXISTS "public"."support";
CREATE TABLE "public"."support" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "title" varchar(255) COLLATE "pg_catalog"."default",
  "system" varchar(255) COLLATE "pg_catalog"."default",
  "date" varchar COLLATE "pg_catalog"."default",
  "work" float4,
  "nonwork" float4,
  "weekend" float4,
  "requestor" varchar(255) COLLATE "pg_catalog"."default",
  "support" varchar(255) COLLATE "pg_catalog"."default",
  "business_bg" text COLLATE "pg_catalog"."default",
  "technical_bg" text COLLATE "pg_catalog"."default",
  "solve" text COLLATE "pg_catalog"."default",
  "issue" varchar(255) COLLATE "pg_catalog"."default",
  "createAt" timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  "type" varchar(50) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."support" OWNER TO "postgres";
COMMENT ON COLUMN "public"."support"."title" IS '标题';
COMMENT ON COLUMN "public"."support"."system" IS '系统';
COMMENT ON COLUMN "public"."support"."type" IS 'MSR-API|NC|Tmall|APP-Backend(四选一)';
COMMENT ON COLUMN "public"."support"."date" IS '时间';
COMMENT ON COLUMN "public"."support"."work" IS '工作耗时';
COMMENT ON COLUMN "public"."support"."nonwork" IS '非工作耗时';
COMMENT ON COLUMN "public"."support"."weekend" IS '周末耗时';
COMMENT ON COLUMN "public"."support"."requestor" IS '请求方';
COMMENT ON COLUMN "public"."support"."support" IS '支持方';
COMMENT ON COLUMN "public"."support"."business_bg" IS '业务背景';
COMMENT ON COLUMN "public"."support"."technical_bg" IS '技术背景';
COMMENT ON COLUMN "public"."support"."solve" IS '解决过程';
COMMENT ON COLUMN "public"."support"."issue" IS 'issue链接';
COMMENT ON COLUMN "public"."support"."createAt" IS '创建时间';

-- ----------------------------
-- Primary Key structure for table support
-- ----------------------------
ALTER TABLE "public"."support" ADD CONSTRAINT "support_pkey" PRIMARY KEY ("id");
